name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin
        
      - name: Build Docker Image
        run: docker build -t badboy2977/tdbackend .
        
      - name: Publish Image to Docker Hub
        run: docker push badboy2977/tdbackend:latest   

  deploy: 
    needs: build
    runs-on: ec2-runner # Replace 'ec2-runner' with the actual label you assigned to your runner
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull badboy2977/tdbackend:latest 
        
      - name: Delete Old Container
        run: docker rm -f springContainer || true
        
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name springContainer badboy2977/tdbackend
